---
- hosts: master
  remote_user: "{{ user }}"
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - gluster/server-prepare
    - { role: gluster/brick-create, brick_device: /dev/xvdb, brick_name: brick0 }
    - { role: gluster/brick-create, brick_device: /dev/xvdc, brick_name: brick1 }
    - gluster/workers-add
    - gluster/volume-create
    - { role: gluster/volume-add-bricks, brick_name: brick1 }
