---
  - name: Add GlusterFS repository and update apt cache
    apt_repository:
      repo: "{{ apt_repository }}"
      mode: '644'
      update_cache: yes
      state: present

  - name: Install GlusterFS
    apt:
      name: "glusterfs-server"
      state: "present"

  - name: Making sure that GlusterFS is started
    service:
      name: glusterd
      state: started
