version: "3"

services:

  web:
    image: jpsecher/get-started:part2
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

  gdash:
    image: kawaz/gdash
    ports:
      - "8081:8080"
    command: gdash --host ip-172-31-6-170.eu-west-1.compute.internal

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      # TODO: Should be taken from ../ansible/group_vars/all swarm_storage_dir.
      - /swarm/volumes:/data
    command: redis-server --appendonly yes
    networks:
      - webnet

networks:
  webnet:
