---
  - name: Add GlusterFS repository and update apt cache
    apt_repository:
      repo: "{{ apt_repository }}"
      mode: '644'
      update_cache: yes
      state: present

  - name: Install GlusterFS
    apt:
      name: "glusterfs-client"
      state: "present"

  - name: Create directory for share
    file: path="{{ swarm_storage_dir }}" state=directory

  - name: Mount replicated data storage
    mount:
      src: "{{ gluster_name }}:/{{ volume_name }}"
      path: "{{ swarm_storage_dir }}"
      fstype: glusterfs
      opts: "defaults,_netdev"
      state: mounted

# sudo apt-get install chrony
# echo 'server 169.254.169.123 prefer iburst' >> /etc/chrony/chrony.conf
# sudo service chrony start
# sudo cat /var/log/chrony/tracking.log
# sudo /etc/init.d/chrony restart
# chronyc sources -v
