---
  - shell: docker swarm leave --force
    ignore_errors: True

  - name: Joining swarm with master {{ master_ip }}
    shell: docker swarm join --token {{ worker_token }} {{ master_ip }}:2377
    register: swarm
