---
- name: Start Swarm master
  hosts: staging-master
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - gluster-create-volume
    - docker
    - docker-swarm-master
