---
- name: Join Swarm cluster
  hosts: staging-workers
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - vault
    - gluster
    - docker
    - docker-swarm-worker
