---
- hosts: staging-node-01-a
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - gluster-prepare
    - gluster-create-volume
    - gluster-mount-volume
    - docker
    - docker-swarm-master
