---
- hosts: swarm-node
  remote_user: "{{ user }}"
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - gluster/client-prepare
    - docker/install-engine
    - docker/swarm-master
